#!/usr/bin/env bash

# Programmer: Niki Mardari
# Purpose:
# Select a batch of RLE images from data/Encoded
# and copy them into data/current_batch for the ESP32 to download.
#
# Input:
# data/Encoded/*.rle
#
# Output:
# data/current_batch/image_0.rle
# data/current_batch/image_1.rle
# data/current_batch/manifest.txt
# data/batch_lastfile.txt

set -e

BATCH_SIZE="${1:-5}"

SOURCE_DIR="data/Encoded"
BATCH_DIR="data/current_batch"
LAST_FILE="data/batch_lastfile.txt"
MANIFEST="$BATCH_DIR/manifest.txt"

mkdir -p "$BATCH_DIR"

mapfile -t files < <(find "$SOURCE_DIR" -maxdepth 1 -type f -name "*.rle" | sort)

if [ "${#files[@]}" -eq 0 ]; then
  echo "No RLE files found in $SOURCE_DIR"
  exit 1
fi

last=""

if [ -f "$LAST_FILE" ]; then
  last=$(cat "$LAST_FILE")
fi

start_index=0

for i in "${!files[@]}"; do
  if [ "${files[$i]}" = "$last" ]; then
    start_index=$(( (i + 1) % ${#files[@]} ))
    break
  fi
done

rm -f "$BATCH_DIR"/*.rle
rm -f "$MANIFEST"

echo "# RLE batch generated by GitHub Actions" > "$MANIFEST"
echo "# batch_id $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$MANIFEST"
echo "# source files:" >> "$MANIFEST"

last_selected=""

for ((n = 0; n < BATCH_SIZE; n++)); do
  index=$(( (start_index + n) % ${#files[@]} ))
  source_file="${files[$index]}"
  output_file="$BATCH_DIR/image_${n}.rle"

  cp "$source_file" "$output_file"

  echo "# image_${n}.rle <- $source_file" >> "$MANIFEST"
  echo "image_${n}.rle" >> "$MANIFEST"

  last_selected="$source_file"
done

echo "$last_selected" > "$LAST_FILE"

echo "Created RLE batch:"
cat "$MANIFEST"